In [73]:
import pandas as pd

In [74]:
temperatures_celsius = pd.Series([25, 26, 27, 28, 29, 30, 31], index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])

In [75]:
temperatures_celsius

Mon    25
Tue    26
Wed    27
Thu    28
Fri    29
Sat    30
Sun    31
dtype: int64

In [76]:
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [77]:
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [78]:
print(s.head())  # View first 5 rows
print(s.tail(3))  # View last 3 rows

0    1
1    2
2    3
3    4
4    5
dtype: int64
7     8
8     9
9    10
dtype: int64

In [79]:
s.describe()

count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
dtype: float64

In [80]:
ss = pd.Series(['a', 'b', 'c', 'a', 'a', 'b', 'c', 'c', 'd'])
print(ss.value_counts())

a    3
c    3
b    2
d    1
Name: count, dtype: int64

In [81]:
print(ss.unique())
print(ss.nunique())

<StringArray>
['a', 'b', 'c', 'd']
Length: 4, dtype: str
4

In [82]:
print(ss.sort_values())  # Sort by values
print(ss.sort_index())   # Sort by index

0    a
3    a
4    a
1    b
5    b
2    c
6    c
7    c
8    d
dtype: str
0    a
1    b
2    c
3    a
4    a
5    b
6    c
7    c
8    d
dtype: str

In [83]:
print(ss.isnull())
print(ss.notnull())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
dtype: bool

In [84]:
import numpy as np
ser = pd.Series([10, 20, np.nan, 40])

# Detect missing values

In [85]:
ser

0    10.0
1    20.0
2     NaN
3    40.0
dtype: float64

In [86]:
ser.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [87]:
ser.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [88]:
ser.fillna(5)

0    10.0
1    20.0
2     5.0
3    40.0
dtype: float64

In [89]:
ser.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [90]:
ser.fillna(5, inplace=True)

0    10.0
1    20.0
2     5.0
3    40.0
dtype: float64

In [91]:
ser

0    10.0
1    20.0
2     5.0
3    40.0
dtype: float64

In [92]:
ser.notnull()

0    True
1    True
2    True
3    True
dtype: bool

In [93]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

In [94]:
data

{'calories': [420, 380, 390], 'duration': [50, 40, 45]}

In [95]:
df = pd.DataFrame(data)

In [96]:
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [97]:
data = {'Name': ['John', 'Emma', 'Ryan', 'Sophia', 'Liam'],
        'Math': [85, 90, 92, 88, 95],
        'Science': [88, 85, 90, 92, 86],
        'History': [75, 80, 85, 88, 90]}

In [98]:
data

{'Name': ['John', 'Emma', 'Ryan', 'Sophia', 'Liam'],
 'Math': [85, 90, 92, 88, 95],
 'Science': [88, 85, 90, 92, 86],
 'History': [75, 80, 85, 88, 90]}

In [99]:
df = pd.DataFrame(data)

In [100]:
df

     Name  Math  Science  History
0    John    85       88       75
1    Emma    90       85       80
2    Ryan    92       90       85
3  Sophia    88       92       88
4    Liam    95       86       90

In [101]:
df = pd.read_csv('diabetess.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'diabetess.csv'

In [ ]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [ ]:
df.shape

(768, 9)

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=768, step=1)

In [ ]:
df.dtypes

Pregnancies                   int64
Glucose                     float64
BloodPressure               float64
SkinThickness               float64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [ ]:
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,NaN,NaN,25.6,0.201,30,0
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
7,10,115.0,NaN,NaN,NaN,35.3,0.134,29,0
8,2,197.0,70.0,45.0,543.0,30.5,0.158,53,1
9,8,125.0,96.0,NaN,NaN,NaN,0.232,54,1

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,763.000000,733.000000,541.000000,394.000000,757.000000,768.000000,768.000000,768.000000
mean,3.845052,121.686763,72.405184,29.153420,155.548223,32.457464,0.471876,33.240885,0.348958
std,3.369578,30.535641,12.382158,10.476982,118.775855,6.924988,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,64.000000,22.000000,76.250000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,29.000000,125.000000,32.300000,0.372500,29.000000,0.000000
75%,6.000000,141.000000,80.000000,36.000000,190.000000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Pregnancies,768.0,3.845052,3.369578,0.000,1.00000,3.0000,6.00000,17.00
Glucose,763.0,121.686763,30.535641,44.000,99.00000,117.0000,141.00000,199.00
BloodPressure,733.0,72.405184,12.382158,24.000,64.00000,72.0000,80.00000,122.00
SkinThickness,541.0,29.153420,10.476982,7.000,22.00000,29.0000,36.00000,99.00
Insulin,394.0,155.548223,118.775855,14.000,76.25000,125.0000,190.00000,846.00
BMI,757.0,32.457464,6.924988,18.200,27.50000,32.3000,36.60000,67.10
DiabetesPedigreeFunction,768.0,0.471876,0.331329,0.078,0.24375,0.3725,0.62625,2.42
Age,768.0,33.240885,11.760232,21.000,24.00000,29.0000,41.00000,81.00
Outcome,768.0,0.348958,0.476951,0.000,0.00000,0.0000,1.00000,1.00

In [ ]:
df['Age'].mean()

33.240885416666664

In [ ]:
df.isnull()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,False,False,False,False,True,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,True,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,True,True,False,False,False,False
767,False,False,False,False,True,False,False,False,False

In [ ]:
df.groupby('Outcome')['Age'].sum()

Outcome
0    15595
1     9934
Name: Age, dtype: int64

In [ ]:
df.groupby('Outcome')['Age'].mean()

Outcome
0    31.190000
1    37.067164
Name: Age, dtype: float64

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

# create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 32, 18, 47, 33],
    'City': ['New York', 'Paris', 'London', 'Tokyo', 'Sydney']
}
df = pd.DataFrame(data)

# access the Name column
names = df['Name']

print(names)

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

In [ ]:
df

      Name  Age      City
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London
3    David   47     Tokyo
4      Eve   33    Sydney

In [ ]:
df['Name']

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

In [ ]:
df[['Name','Age']]

      Name  Age
0    Alice   25
1      Bob   32
2  Charlie   18
3    David   47
4      Eve   33

In [ ]:
single_row = df.loc[2]

In [ ]:
single_row

Name    Charlie
Age          18
City     London
Name: 2, dtype: object

In [ ]:
row_list = df.loc[[0, 3, 4]]
row_list

    Name  Age      City
0  Alice   25  New York
3  David   47     Tokyo
4    Eve   33    Sydney

In [ ]:
df

      Name  Age      City
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London
3    David   47     Tokyo
4      Eve   33    Sydney

In [ ]:
column_list = df.loc[:,['Name', 'Age']]

In [ ]:
column_list

      Name  Age
0    Alice   25
1      Bob   32
2  Charlie   18
3    David   47
4      Eve   33

In [ ]:
column_list = df.loc[0:3,['Name', 'Age']]

In [ ]:
column_list

      Name  Age
0    Alice   25
1      Bob   32
2  Charlie   18
3    David   47

In [ ]:
specific_value = df.loc[1, 'Name']
specific_value

'Bob'

In [ ]:
slice_rows = df.loc[1:3]
slice_rows

      Name  Age    City
1      Bob   32   Paris
2  Charlie   18  London
3    David   47   Tokyo

In [ ]:
df

      Name  Age      City
0    Alice   25  New York
1      Bob   32     Paris
2  Charlie   18    London
3    David   47     Tokyo
4      Eve   33    Sydney

In [ ]:
single_row = df.iloc[2]
single_row

Name    Charlie
Age          18
City     London
Name: 2, dtype: object

In [ ]:
row_list = df.iloc[[0, 3, 4]]

In [ ]:
row_list

    Name  Age      City
0  Alice   25  New York
3  David   47     Tokyo
4    Eve   33    Sydney

In [ ]:
slice_columns = df.iloc[2:, 0:2]

In [ ]:
slice_columns

      Name  Age
2  Charlie   18
3    David   47
4      Eve   33

In [ ]:
boolean_index = df.loc[df['Age'] > 30]

In [ ]:
boolean_index

    Name  Age    City
1    Bob   32   Paris
3  David   47   Tokyo
4    Eve   33  Sydney